spring:
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  database:
    platform: h2
    url: jdbc:h2:tcp://localhost:9092/mem:bookdb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
kakao:
  rest-api-key: a461f060c676aa869b7ff6b46ccf2d72

jwt:
  secret-key: booksearchSecretKeyeeeeeee